
server:
  port: 8222
eureka:
  instance:
    hostname: localhost
spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id : customer-service
          #uri: http://localhost:9001
          uri: lb://customer-service
          predicates:
            - Path=/cus/**
        - id: coupon
          #uri: http://localhost:9000
          uri: lb://coupon-service
          predicates:
            - Path=/coupon/**
        - id: Admin
          #uri:http://localhost:9003
          uri: lb://Admin-service
          predicates:
             - Path=/admin/**